### ISSUE TITLE
Hide gradual minutes (1,2,3,4) and show by click on empty space or hover

### ISSUE THREAD

**Issue by yaitskov** [luncheon/clocklet#4]
In my case showing buttons for minutes 1, 2, 3 is overkill.

This UI items should be less obvious.
let's add flag to hide them by default and show if user clicks in empty space between 0 and 5 minutes or hover mouse cursor there.

**Comment by luncheon** [comment]
Minutes that do not end with `0` or `5` can be hidden with following CSS.

```css
.clocklet-tick--minute:not([data-clocklet-tick-value$="0"]):not([data-clocklet-tick-value$="5"]) {
  display: none;
}
``` 

If you do not want to hide the selected minute, use following CSS.

```css
.clocklet-tick--minute:not([data-clocklet-tick-value$="0"]):not([data-clocklet-tick-value$="5"]):not(.clocklet-tick--selected) {
  display: none;
}
```

https://codepen.io/luncheon/pen/ExyzxBZ
